### ISSUE TITLE
item dk

### ISSUE THREAD

**Issue by davidwow1024** [Mistixx/Nordrassil-Report#3]
https://es.wowhead.com/item=39700/cuerno-de-razaescarcha
el core lo detecta como un hack y saca los jugadores

**Comment by d3athbl0w** [comment]
Fixed on:

https://github.com/Mistixx/Nordrassil-Legion/commit/bf853f8d07cc9725c02e3162fc9ea483edf1f641

**Comment by davidwow1024** [comment]
Reparado
